# Generated by Django 3.2.4 on 2021-06-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_course', to='myapi.course'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_course', to='myapi.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.contact'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.category'),
        ),
    ]
