# Generated by Django 3.2.4 on 2021-06-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210614_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_course', to='myapi.course'),
        ),
    ]
