# Generated by Django 3.2.4 on 2021-06-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_branch_branch_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_course', to='myapi.course'),
        ),
    ]
