# Generated by Django 3.2.4 on 2021-06-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_branch_branch_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
