# Generated by Django 3.2.4 on 2021-06-18 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210618_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contacts_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_course', to='myapi.contact'),
        ),
    ]
