# Generated by Django 3.2.4 on 2021-06-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_alter_course_course_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_contacts',
        ),
    ]
