# Generated by Django 3.2.4 on 2021-06-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_remove_course_course_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='myapi.course'),
        ),
    ]
