# Generated by Django 3.2.4 on 2021-06-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_alter_branch_branch_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='course',
            new_name='contact_course',
        ),
    ]
